### ISSUE TITLE
Basic example does not work in Python 3.12 ConnectionResetError (Connection Lost)

### ISSUE THREAD

**Issue by camux** [OpenBB-finance/pywry#120]
This basic example in README does not work:

Ubuntu 24.04 
Python 3.12.3

Throw this error.

Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/psk/Dev/LAB/pywryapp/.pwenv/lib/python3.12/site-packages/pywry/core.py", line 384, in run
    asyncio.run(self.run_backend())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/psk/Dev/LAB/pywryapp/.pwenv/lib/python3.12/site-packages/pywry/core.py", line 358, in run_backend
    await self.run_backend()
  File "/home/psk/Dev/LAB/pywryapp/.pwenv/lib/python3.12/site-packages/pywry/core.py", line 339, in run_backend
    await self.runner.stdin.drain()
  File "/usr/lib/python3.12/asyncio/streams.py", line 392, in drain
    await self._protocol._drain_helper()
  File "/usr/lib/python3.12/asyncio/streams.py", line 166, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost

It seems that the error is related with drain(), but I am not asyncio expert

**Comment by Charles546** [comment]
Ubuntu 24.04 came with libwebkit2gtk-4.1-dev, but pywry requires 4.0. Use older version of Ubuntu, or somehow get the 4.0 installed. I was able to get it working by installing the 4.0 from jammy suite.  Looks like these guys are slow in catching up with releases.
